#!/bin/bash
# AI-Native SDLC — the engine-map fixture set: what scripts/apply-engines.sh
# says about each case, and the TypeScript mirror the mod's tests read.
#
# Sourced by tests/test_apply_engines.sh, which asserts every case's verdict
# and that the mirror is a fresh rendering. Run directly to (re)write them:
#
#   bash tests/engine_map_cases.sh --write
#
# A case is three files in tests/fixtures/engine-map/: <case>.map.conf (the
# engine map), <case>.roles.conf (the role manifest) and <case>.expected (the
# verdict). The verdict is never written by hand: it is what the script did.
#
#   accept                      the script exited 0, followed by one line per
#   <agent>\t<first entry>      agent the manifest binds, sorted, naming the
#                               model the script wrote into that agent
#   refuse map <line>           the script exited 2, one line per fault it
#   refuse roles <line>         reported, in the order it reported them
#
# The table comes from the agent files the script rewrote, not from a parser of
# ours: a first run with no agents installed names every agent the manifest
# binds (as "not installed" warnings), one stub per name is installed, and a
# second run writes each stub's model line.
#
# Bash 3.2: no associative arrays, no mapfile.

# The mirror's path, relative to the checkout.
ENGINE_MAP_MIRROR="adapters/claude/skills/sdlc-engine-map/hooks/map.fixtures.ts"

# The cases REQ-MOD-015 requires, one per grammar point: the one list of them.
# tests/test_apply_engines.sh reads it, and the mirror carries it to the mod's
# tests as REQUIRED.
ENGINE_MAP_REQUIRED="whitespace crlf dup-map-first-wins dup-manifest-last-wins
  empty-element-map empty-element-trailing empty-element-manifest
  undefined-role comma-role malformed whole-file-refused
  map-error-cascades dup-manifest-bad-first quirks empty-manifest"

_ENGINE_MAP_REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# engine_map_verdict <cases-dir> <case> <tmp-parent> — print the script's
# verdict on the case. Anything the script did that is neither shape prints an
# `unexpected` line, which matches no `.expected` file.
engine_map_verdict() {
  local dir="$1" c="$2" h out rc map manifest agents a
  h=$(mktemp -d "$3/case-home.XXXXXX")
  h=$(cd "$h" && pwd)
  mkdir -p "$h/.claude/agents"
  map="$h/.claude/sdlc-engines.conf"
  manifest="$h/.claude/agents/roles.conf"
  cp "$dir/$c.map.conf" "$map"
  cp "$dir/$c.roles.conf" "$manifest"
  out="$h/run1.out"
  rc=0
  env -u SDLC_AGENTS_DIR HOME="$h" \
    bash "$_ENGINE_MAP_REPO/scripts/apply-engines.sh" > "$out" 2>&1 || rc=$?

  if [ "$rc" -eq 2 ]; then
    # `apply-engines.sh: <file>:<line>: <message>: <text>` — the file decides
    # map or roles, compared as a fixed string (a temp path is not a regex).
    awk -v map="apply-engines.sh: $map:" -v man="apply-engines.sh: $manifest:" '
      index($0, map) == 1 { r = substr($0, length(map) + 1); sub(/:.*/, "", r); print "refuse map " r; n++; next }
      index($0, man) == 1 { r = substr($0, length(man) + 1); sub(/:.*/, "", r); print "refuse roles " r; n++; next }
      END { if (n == 0) print "unexpected: exit 2 with no fault line" }
    ' "$out"
    return 0
  fi
  if [ "$rc" -ne 0 ]; then
    printf 'unexpected: exit %s\n' "$rc"
    return 0
  fi

  agents="$h/agents.list"
  sed -n 's/^WARNING: .* names "\(.*\)", which is not installed at .*$/\1/p' "$out" |
    LC_ALL=C sort -u > "$agents"
  while IFS= read -r a; do
    printf -- '---\nname: %s\nmodel: unset-before-the-run\n---\n' "$a" \
      > "$h/.claude/agents/$a.md"
  done < "$agents"
  rc=0
  env -u SDLC_AGENTS_DIR HOME="$h" \
    bash "$_ENGINE_MAP_REPO/scripts/apply-engines.sh" > "$h/run2.out" 2>&1 || rc=$?
  if [ "$rc" -ne 0 ]; then
    printf 'unexpected: second run exit %s\n' "$rc"
    return 0
  fi
  printf 'accept\n'
  while IFS= read -r a; do
    printf '%s\t%s\n' "$a" "$(awk '
      NR == 1 { if ($0 != "---") exit; fm = 1; next }
      fm && $0 == "---" { exit }
      fm && /^model:/ { sub(/^model:[ \t]*/, ""); print; exit }
    ' "$h/.claude/agents/$a.md")"
  done < "$agents"
}

# engine_map_ts_mirror <cases-dir> — print the TypeScript module holding the
# required case names and every case's three files verbatim, in case-name
# order.
engine_map_ts_mirror() {
  local dir="$1" m c first=1
  printf '%s\n' "// GENERATED by tests/engine_map_cases.sh --write from tests/fixtures/engine-map/."
  printf '%s\n' "// Do not edit: tests/test_apply_engines.sh fails when this is not a fresh rendering."
  printf 'export const REQUIRED: readonly string[] = %s\n' \
    "$(printf '%s\n' "$ENGINE_MAP_REQUIRED" | tr -s ' ' '\n' | sed '/^$/d' | jq -R . | jq -cs .)"
  printf '%s\n' "export type EngineMapCase = { name: string; map: string; roles: string; expected: string }"
  printf '%s\n' "export const CASES: readonly EngineMapCase[] = ["
  for m in "$dir"/*.map.conf; do
    [ -f "$m" ] || continue
    c=$(basename "$m" .map.conf)
    [ "$first" -eq 1 ] || printf ',\n'
    first=0
    jq -cn --arg name "$c" \
      --rawfile map "$dir/$c.map.conf" \
      --rawfile roles "$dir/$c.roles.conf" \
      --rawfile expected "$dir/$c.expected" \
      '{name: $name, map: $map, roles: $roles, expected: $expected}' | tr -d '\n'
  done
  printf '\n]\n'
}

# --write: regenerate every `.expected` from the script, then the mirror.
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  set -u
  if [ "${1:-}" != "--write" ]; then
    printf 'usage: bash %s --write\n' "$0" >&2
    exit 2
  fi
  cases="$_ENGINE_MAP_REPO/tests/fixtures/engine-map"
  scratch=$(mktemp -d "${TMPDIR:-/tmp}/sdlc-engine-map-cases.XXXXXX") || exit 2
  trap 'rm -rf "$scratch"' EXIT
  for m in "$cases"/*.map.conf; do
    [ -f "$m" ] || continue
    c=$(basename "$m" .map.conf)
    engine_map_verdict "$cases" "$c" "$scratch" > "$cases/$c.expected"
    printf '%s: %s\n' "$c" "$(tr '\n' ';' < "$cases/$c.expected")"
  done
  engine_map_ts_mirror "$cases" > "$_ENGINE_MAP_REPO/$ENGINE_MAP_MIRROR"
  printf 'wrote %s\n' "$ENGINE_MAP_MIRROR"
fi
